#include "stm32f10x.h"

int main()
{
	RCC->APB2ENR |= (RCC_APB2ENR_IOPAEN | RCC_APB2ENR_AFIOEN);
	GPIOA->CRL |= GPIO_CRL_MODE0_1;
	GPIOA->CRL &= ~GPIO_CRL_CNF0_0;
	
	RCC->APB1ENR |= RCC_APB1ENR_TIM2EN;
  TIM2->CR1 |= TIM_CR1_ARPE;
  TIM2->CCMR1 |= TIM_CCMR1_OC2PE;
  TIM2->CCMR1 |= (TIM_CCMR1_OC2M_2 | TIM_CCMR1_OC2M_1);
  TIM2->ARR = 71999;
  TIM2->CCR2 = 1000;
  TIM2->CCER |= TIM_CCER_CC2E;
	TIM2->DIER |= TIM_DIER_UIE;
  TIM2->CR1 |= TIM_CR1_CEN;
	NVIC_EnableIRQ(TIM2_DAC_IRQn);
	
	while(1) {
	
	}
}
